<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>

    </head>

    <body class="yui-skin-sam" onload="<?php if ($this->preview) : ?>open_preview('/<?php echo $this->escapeHtmlAttr($this->moduleName) ?>/<?php echo $this->escapeHtmlAttr($this->pageName) ?>?preview=publishing')<?php endif; ?>">

        <div id="top"><!-- Start top area -->

            <div class="title">Publish:
                <?php echo $this->escapeHtml($this->moduleName) ?> - <i><?php echo $this->escapeHtml($this->pageName) ?></i></div>
            <?php echo $this->messages() ?>
            <div class="info"><img src="/images/required_star.png" alt="Required"> indicates required field</div>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->setAttribute('name', 'main')->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>

            <?php echo $this->adminFormElement($form->get('from')) ?>
            <?php echo $this->adminFormElement($form->get('id')) ?>
            <?php echo $this->adminFormElement($form->get('partial')) ?>
            <?php echo $this->adminFormElement($form->get('token')) ?>

            <div id="stage"><!-- Start stage area -->

                <?php
                $freeBlocks = $form->get('freeBlocks')->getFieldsets();
                $blockSequences = $form->get('blockSequences')->getFieldsets();
                ?>

                <?php if ($freeBlocks || $blockSequences) : ?>
                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Blocks</div>

                        <?php foreach ($freeBlocks as $freeBlock) : ?>
                        <div class="form-element">
                            <label class="lined-up"><?php echo $freeBlock->getLabel() ?></label>
                            <div class="form-inputs line-up">
                                <table class="table" style="background-color: #ffffff;">
                                    <thead>
                                        <tr>
                                            <th>Block</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                <?php echo $this->formElement($freeBlock->get('id')); ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <?php endforeach; ?>

                        <?php foreach ($blockSequences as $blockSequence) : ?>

                        <?php

                        $idOptions = [];

                        foreach ($form->getBlockValueOptions() as $blockTypeName => $options) {
                            foreach ($options['options'] as $value => $label) {
                                $idOptions[$value] = $blockTypeName . ' ' . $label;
                            }
                        }

                        $idNameTpl = $blockSequence->getName() . '[blocks][#][id]';
                        $orderByNameTpl = $blockSequence->getName() . '[blocks][#][orderBy]';
                        $numCurrentBlocksName = $blockSequence->getName() . '[numCurrentBlocks]';
                        $numNewBlocksName = $blockSequence->getName() . '[numNewBlocks]';
                        ?>

                        <div class="form-element">
                            <label class="lined-up"><?php echo $blockSequence->getLabel() ?></label>
                            <div class="form-inputs line-up">
                                <table class="table" style="background-color: #ffffff;" id="<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>">
                                    <thead>
                                        <tr>
                                            <th>Block</th>
                                            <th colspan="3">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>

                                <script type="text/javascript">

                                    <?php foreach ($blockSequence->get('blocks') as $sequenceBlock) : ?>

                                    addRow(
                                    'saved',
                                    '<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>',
                                    [
                                        '<?php echo $orderByNameTpl; ?>',
                                        '<?php echo $this->escapeJs($sequenceBlock->get('orderBy')->getValue()); ?>'
                                    ],
                                    [
                                        [
                                            'createBlockIdSelect',
                                            '<?php echo $idNameTpl; ?>',
                                            '<?php echo $this->escapeJs($sequenceBlock->get('id')->getValue()); ?>',
                                            [['', '']
                                            <?php foreach ($idOptions as $value => $label) : ?>
                                            ,['<?php echo $this->escapeJs($value); ?>', '<?php echo $this->escapeJs($label); ?>']
                                            <?php endforeach; ?>],
                                            false
                                        ]
                                    ],
                                    '<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>',
                                    '<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>',
                                    'en',
                                    'en',
                                    ['en']);

                                    <?php endforeach; ?>

                                    sortTable('<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>', 0, 0, 'numeric', 'ASC');
                                </script>

                                <p><a class="link" href="javascript:void(0)" onclick="addBlankRow(
                                        '<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>',
                                        20,
                                        [
                                            '<?php echo $orderByNameTpl; ?>',
                                            ''
                                        ],
                                        [
                                            [
                                                'createBlockIdSelect',
                                                '<?php echo $idNameTpl; ?>',
                                                '',
                                                [
                                                    ['', '']
                                                    <?php foreach ($idOptions as $value => $label) : ?>
                                                    ,['<?php echo $this->escapeJs($value); ?>', '<?php echo $this->escapeJs($label); ?>']
                                                    <?php endforeach; ?>
                                                ],
                                                false
                                            ]
                                        ],
                                        '<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>',
                                        '<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>',
                                        'en',
                                        'en',
                                        ['en']);">Add block</a></p>

                                <input type="hidden" name="<?php echo $numCurrentBlocksName; ?>" value="<?php echo count($blockSequence->get('blocks')); ?>" id="<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>">
                                <input type="hidden" name="<?php echo $numNewBlocksName; ?>" value="0" id="<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>">

                            </div>
                            <div class="clear"></div>
                        </div>
                        <?php endforeach; ?>

                    </div>
                </div><!-- End fieldset -->
                <?php else : ?>
                <p>No publishing options available for this page</p>
                <?php endif; ?>

            </div><!-- End stage area -->

            <div class="submit-area">

                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('preview')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('preview')) ?>
                    </div>
                </div>

                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('publish')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('publish')) ?>
                    </div>
                </div>

            </div>

        <?php echo $this->form()->closeTag() ?>
    </body>
</html>
