<?php
if ($this->preview) :

    $url = $this->url($this->moduleName, ['action' => $this->pageName], [
        'query' => [
            'preview' => 'publishing',
        ],
    ]);

    $this->inlineScript()->appendScript("open_preview('{$url}')");

endif;
?>

        <div class="row">
            <div class="col-md-12">

                <h1>Publish
                <?php echo $this->escapeHtml($this->moduleName) ?> <small><?php echo $this->escapeHtml($this->pageName) ?></small></h1>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main');
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('from')) ?>
                    <?php echo $this->adminFormElement($form->get('id')) ?>
                    <?php echo $this->adminFormElement($form->get('partial')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <?php
                    $freeBlocks = $form->get('freeBlocks')->getFieldsets();
                    $blockSequences = $form->get('blockSequences')->getFieldsets();
                    ?>

                    <?php if ($freeBlocks || $blockSequences) : ?>
                    <fieldset>
                        <legend>Blocks</legend>

                        <?php foreach ($freeBlocks as $freeBlock) : ?>
                        <div class="form-element">
                            <label class="lined-up"><?php echo $freeBlock->getLabel() ?></label>
                            <div class="form-inputs line-up">
                                <table class="table" style="background-color: #ffffff;">
                                    <thead>
                                        <tr>
                                            <th>Block</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                <?php echo $this->formElement($freeBlock->get('id')); ?>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <?php endforeach; ?>

                        <?php foreach ($blockSequences as $blockSequence) : ?>

                        <?php

                        $idOptions = [];

                        foreach ($form->getBlockValueOptions() as $blockTypeName => $options) {
                            foreach ($options['options'] as $value => $label) {
                                $idOptions[$value] = $blockTypeName . ' ' . $label;
                            }
                        }

                        $idNameTpl = $blockSequence->getName() . '[blocks][#][id]';
                        $orderByNameTpl = $blockSequence->getName() . '[blocks][#][orderBy]';
                        $numCurrentBlocksName = $blockSequence->getName() . '[numCurrentBlocks]';
                        $numNewBlocksName = $blockSequence->getName() . '[numNewBlocks]';
                        ?>

                        <div class="form-element">
                            <label class="lined-up"><?php echo $blockSequence->getLabel() ?></label>
                            <div class="form-inputs line-up">
                                <table class="table" style="background-color: #ffffff;" id="<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>">
                                    <thead>
                                        <tr>
                                            <th>Block</th>
                                            <th colspan="3">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>

                                <script type="text/javascript">

                                    <?php foreach ($blockSequence->get('blocks') as $sequenceBlock) : ?>

                                    addRow(
                                    'saved',
                                    '<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>',
                                    [
                                        '<?php echo $orderByNameTpl; ?>',
                                        '<?php echo $this->escapeJs($sequenceBlock->get('orderBy')->getValue()); ?>'
                                    ],
                                    [
                                        [
                                            'createBlockIdSelect',
                                            '<?php echo $idNameTpl; ?>',
                                            '<?php echo $this->escapeJs($sequenceBlock->get('id')->getValue()); ?>',
                                            [['', '']
                                            <?php foreach ($idOptions as $value => $label) : ?>
                                            ,['<?php echo $this->escapeJs($value); ?>', '<?php echo $this->escapeJs($label); ?>']
                                            <?php endforeach; ?>],
                                            false
                                        ]
                                    ],
                                    '<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>',
                                    '<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>',
                                    'en',
                                    'en',
                                    ['en']);

                                    <?php endforeach; ?>

                                    sortTable('<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>', 0, 0, 'numeric', 'ASC');
                                </script>

                                <p><a class="link" href="javascript:void(0)" onclick="addBlankRow(
                                        '<?php echo $this->adminFormElement()->nameToId($blockSequence->getName()) . '-en'; ?>',
                                        20,
                                        [
                                            '<?php echo $orderByNameTpl; ?>',
                                            ''
                                        ],
                                        [
                                            [
                                                'createBlockIdSelect',
                                                '<?php echo $idNameTpl; ?>',
                                                '',
                                                [
                                                    ['', '']
                                                    <?php foreach ($idOptions as $value => $label) : ?>
                                                    ,['<?php echo $this->escapeJs($value); ?>', '<?php echo $this->escapeJs($label); ?>']
                                                    <?php endforeach; ?>
                                                ],
                                                false
                                            ]
                                        ],
                                        '<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>',
                                        '<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>',
                                        'en',
                                        'en',
                                        ['en']);">Add block</a></p>

                                <input type="hidden" name="<?php echo $numCurrentBlocksName; ?>" value="<?php echo count($blockSequence->get('blocks')); ?>" id="<?php echo $this->adminFormElement()->nameToId($numCurrentBlocksName); ?>">
                                <input type="hidden" name="<?php echo $numNewBlocksName; ?>" value="0" id="<?php echo $this->adminFormElement()->nameToId($numNewBlocksName); ?>">

                            </div>
                            <div class="clear"></div>
                        </div>
                        <?php endforeach; ?>

                    </fieldset>
                    <?php else : ?>
                    <p>No publishing options available for this page</p>
                    <?php endif; ?>

                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2">

                            <?php
                            $form->get('preview')->setAttribute('class', 'btn btn-default');
                            echo $this->formElement($form->get('preview'));
                            ?>

                            <?php
                            $form->get('publish')->setAttribute('class', 'btn btn-primary');
                            echo $this->formElement($form->get('publish'));
                            ?>

                        </div>
                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
